charging_network_topology: None
charging_station:
  max_charge_current: 32
  max_discharge_current: -32
  min_charge_current: 0
  min_discharge_current: 0
  phases: 3
  voltage: 400
day: 17
demand_response:
  event_capacity_percentage_mean: 35
  event_capacity_percentage_std: 5
  event_length_minutes_max: 60
  event_length_minutes_min: 60
  event_start_hour_mean: 12
  event_start_hour_std: 2
  events_per_day: 1
  include: false
  notification_of_event_minutes: 60
discharge_price_factor: 1
ev:
  battery_capacity: 70
  charge_efficiency: 1
  desired_capacity: 1
  discharge_efficiency: 1
  ev_phases: 3
  max_ac_charge_power: 22
  max_dc_charge_power: 50
  max_discharge_power: -22
  min_ac_charge_power: 0
  min_battery_capacity: 15
  min_discharge_power: 0
  min_emergency_battery_capacity: 15
  min_time_of_stay: 200
  transition_soc: 1
  transition_soc_multiplier: 50
ev_specs_file: ./ev2gym/data/ev_specs_v2g_enabled2024.json
heterogeneous_ev_specs: false
hour: 5
inflexible_loads:
  forecast_mean: 30
  forecast_std: 5
  include: false
  inflexible_loads_capacity_multiplier_mean: 1
minute: 0
month: 1
network_info:
  branch_info_file: ./ev2gym/data/network_data/node_123/Lines_123.csv
  bus_info_file: ./ev2gym/data/network_data/node_123/Nodes_123.csv
  load_multiplier: 3
  pv_scale: 80
  s_base: 1000
  vm_pu: 1.0
number_of_charging_stations: 500
number_of_ports_per_cs: 1
number_of_transformers: -1
pf_solver: Laurent
power_setpoint_enabled: true
power_setpoint_flexiblity: 80
random_day: true
random_hour: false
scenario: public
simulate_grid: true
simulation_days: weekdays
simulation_length: 300
solar_power:
  forecast_mean: 20
  forecast_std: 5
  include: false
  solar_power_capacity_multiplier_mean: 1
spawn_multiplier: 5
timescale: 15
tr_seed: -1
transformer:
  max_power: 200
v2g_enabled: true
year: 2022
